### PR TITLE
Move state to ViewEventListener

### PR DESCRIPTION
**Pull request by rwols**
In this (unfinished) PR I'll keep everyone updated on my findings for moving state to a ViewEventListener.

Note that for some reason the TerminalView class never gets deleted, even with an unregister class method for TerminalViewManager and even if they are weak references. I suspect there are some circular references between TerminalView and SublimeTerminalBuffer.

### CODE REVIEW

**Comment by rwols** [comment]
This is definitely more work than I expected 😄

**Comment by Wramberg** [comment]
I'm not entirely sure about what you are trying to achieve ;-) My thought was to use the manager class in more places to retrieve a reference to the terminal view.

Maybe the circular dependency is the sublime_buffer saving the callback on the view right now ? That could e.g. be put into the manager class.

**Comment by rwols** [comment]
> Maybe the circular dependency is the sublime_buffer saving the keypress callback on the view right now ? That could e.g. be put into the manager class.

That's a possibility, yeah. Another thing I noticed is that the update thread keeps a reference to `self`, so, that should be a weakref (the update thread should not own an instance).

> I'm not entirely sure about what you are trying to achieve

The most "natural" way to attach state to a sublime.View is to have a sublime_pugin.ViewEventListener that holds that state. What I'm struggling with right now is how you use TerminalViewUpdate, there's all sorts of stuff happening there. I'll see what happens :)

**Comment by Wramberg** [comment]
Alright. Just seems like you're doing a whole lot of refactoring that I might not be able to get behind. Would be great to see what you mean with some examples though so by all means, please carry on :-)

**Comment by rwols** [comment]
Yeah, these commits are temporary, please wait 😄 

The main two problems I have is that a TerminalView does not get cleaned up properly, and that state is attached to a sublime.View object. I'm off to bed now.

**Comment by rwols** [comment]
This PR is a mess now, but I'm getting closer to what I'm trying to achieve ;)

**Comment by rwols** [comment]
Okay. I fixed the multiple instance bug I was experiencing. It was because the `__init__` of `TerminalView2` was doing `self.view.settings().set(... ,...)`. These changes to the settings somehow cause Sublime to re-initialize ViewEventListeners, making duplicates in the process. This seems like a bug on Sublime's side, but I'm not sure.

This PR works now, but, as you already discovered, the bottleneck is the ST api which is *super slow* right now. This is because `_update_line_content` is called a bunch of times, each time calling into the ST api. I have now found the heart of the problem.

**Comment by Wramberg** [comment]
Yeah there's alot going on so it might be hard to merge in. Regarding the cleanup I fixed the issues by setting keypress to None when closing the Sublime terminal buffer. From fdd7e610f05341310f69dc2166f7f8b70f30cd0c everything is cleaned up nicely as verified by the debug logging.

**Comment by rwols** [comment]
> everything is cleaned up nicely as verified by the debug logging.

I experienced OSErrors at some point. We also need to close the file-descriptors `self._pty` and `self._pts` with `os.close` in the `__del__` of `LinuxPty` to solve this I think.

**Comment by Wramberg** [comment]
Ah good point. Should be fixed with b692cd9e6a8605fd8f56dbe59e3e4deaccdba609. I don't like using destructors in Python like you would in e.g. C++ due the nature of pythons garbage collection so I put in the stop method instead. Should yield the same result :-)

**Comment by rwols** [comment]
I'm a C++ guy so I love destructors ;).

**Comment by Wramberg** [comment]
> I'm a C++ guy so I love destructors ;).

Me too :-). Just too bad Python doesn't really support the RAII idiom like C++. Guess that's the price we pay to have automatic garbage collection ;-)

**Comment by rwols** [comment]
Isn't the GC just reference counting? If you just keep your ownership semantics correct, there's no worries in using `__del__`.

**Comment by Wramberg** [comment]
To me its a big problem you dont know when your object is GCed. It could be right away or as the very last thing before the program exits. This limits what you can do in the destructor. As the python docs saids 

Some objects contain references to “external” resources such as open files or windows. It is understood that these resources are freed when the object is garbage-collected, but since garbage collection is not guaranteed to happen, such objects also provide an explicit way to release the external resource, usually a close() method.

I think they are referring to cyclic dependencies and/or exceptions when they say GC is not guaranteed. Oddly enough the GC can figure out cyclic references and free the objects UNLESS they have __del__ methods.

**Comment by rwols** [comment]
So, if our ownership semantics are worked out, `__del__` should prove no problem. My experience with ViewEventListener is as follows:

```python
import sublime_plugin

class TestThing(sublime_plugin.ViewEventListener):

    @classmethod
    def is_applicable(cls, settings):
        return settings.get("test", False)

    def __init__(self, view):
        super(TestThing, self).__init__(view)
        print("Hello!")

    def __del__(self):
        print("Goodbye!")
        # ViewEventListener doesn't have a del method
```
The console will print:
```
>>> view.settings().set("test", True)
Hello!
>>> view.settings().set("test", False)
Goodbye!
```
If you close the view without setting `"test"` to `False`, the EventListener will close too, albeit somewhat later, but that doesn't matter. My guess is that ST keeps an internal view object alive a little bit longer.

This prompted me to rethink the whole class design.

```
CURRENT SITUATION:

TerminalViewManager
 |
 | strong references
 |
 |
 V             has a
TerminalView ---------> ConsoleLogger
 |   ^       ---------> PyteTerminalEmulator
 |   |       ---------> LinuxPty
 |   |
 |   +---------[strong references]------ TerminalViewManager
 |
 | has a
 V                      strong references
SublimeTerminalBuffer <------------------ SublimeTerminalBufferManager
 |
 | has a
 |
 V
sublime.View



PROPOSAL:

ViewEventListener
  |
  | is baseclass of
  V
ConsoleLogger          [__del__ prints something like "goodbye"]
  |                    [another advantage: ConsoleLogger can print the name of the view with self.view]
  |
  | is baseclass of
  V
LinuxPty               [__del__ closes the file-descriptors]
  |
  | is baseclass of
  |
  V           weak references
TerminalView <--------------- class _instances, plays the role of the manager too
  |          <--------------- threading.Thread that runs _main_update_loop
  | has a
  |           [ is_applicable when settings.get("_terminal_view") is True]
  |           [__del__ joins the threading.Thread]
  |
  V
PyteTerminalEmulator

SublimeTerminalBuffer and TerminalView merged into 1 class
Closing the view automatically destroys a TerminalView!
Setting "_terminal_view" to False destroys the TerminalView, too

```

**Comment by rwols** [comment]
I'll close this for now, no point in leaving this open.

**Pull request closed without merging**
