### PR TITLE
Allow snippet-like variables for cwd

### PR DESCRIPTION
**Pull request by rwols**
Allow snippet-like variables for cwd.

### CODE REVIEW

**Comment by Wramberg** [comment]
For some reason sublime.expand_variables did not work as expected which is why it was removed. I kept seeing terminals opened with cwd for another file or in the plugin folder. Maybe we should instead support users setting the key to use in self.window.extract_variables() ?

**Comment by rwols** [comment]
> I kept seeing terminals opened with cwd for another file or in the plugin folder.

Hmm... Doesn't happen on my machine. Could you maybe give an example of this happening?

**Comment by Wramberg** [comment]
Looking over the old code maybe it was the use of the "project_path" key that didnt work too well for me. Maybe when the current file wasnt in a project it would still return a weird path - dont know just speculating.

**Comment by rwols** [comment]
Yes, `$project_path` only exists when you open a .sublime-project. `$folder` should always exist I think. I haven't looked through the commits but if `$project_path` was used, then that's probably a mistake.

**Comment by Wramberg** [comment]
Regardless this code should function exactly like before just with the snippet option again so lets merge it in and see how testing goes.

**Comment by rwols** [comment]
OK, I just checked all cases:

1. If you open a new window with a single file (e.g. `subl -n foo.txt`), then `$folder` doesn't exist, but `$file_path` exists, so `${folder:${file_path}}` wlll select `$file_path`.
2. If you open a new window with a folder (e.g. `subl path/to/folder`), then `$folder` exists. So `${folder:${file_path}}` will select `$folder`.
3. If you open a project, then `$folder` still exists along with `$project_path`.

**Comment by Wramberg** [comment]
Great 👍

**Comment by rwols** [comment]
Although it's `${file_path:${folder}}` in the source code, so, you'll get this behavior:

1. If the view is attached to something on disk, it'll open the dir of the file.
2. If the view is not attached to something on disk, it'll try the base folder.
3. If that doesn't work, that means you opened a new window with a fresh view not attached to any file on disk, so it'll revert to the home folder.

**Pull request merged**
