### PR TITLE
exec command -> terminal_view_exec command

### PR DESCRIPTION
**Pull request by rwols**
This adds a command called TerminalViewExecCommand. In a Sublime build system, you can use this command for the `"target"` value. You can then use the keyboard to give input to whatever command that you're building/executing.

For example, consider this `.sublime-project`:

```json
{
  "build_systems":
  [
    {
      "name": "My Build",
      "shell_cmd": "c++ program.c -o program",
      "working_dir" "${project_path}"
      "variants":
      [
        {
          "name": "Run program",
          "shell_cmd": "./program",
          "working_dir": "${project_path}"
        }
      ]
    }
  ],
  "folders":
  [
    {
      "path": "."
    }
  ],
  "settings":
  {
  }
}
```
A problem occurs when `./program` wants input interactively. You cannot pass this information with the current command that runs (`exec`). So, you can replace it with:
```json
        {
          "target": "terminal_view_exec",
          "name": "Run program",
          "shell_cmd": "./program",
          "working_dir": "${project_path}"
        }
```
and that should be all that's necessary.

One problem I'm encountering though, is that when the program exits, the tab is closed automatically too. Do you have any suggestions on fixing this? My thought was to add an `autoclose` argument. That gets saved in the settings object as `"terminal_view_close_view_too"`. Normally, this is always set to `True`. When it's `False`, the SublimeTerminalBuffer should not close the view but instead flush the last remaining output. It's almost working but I need to do a few more tweaks.

### CODE REVIEW

**Comment by Wramberg** [comment]
What the status on this @rwols ? Seems like a nice addition - I would prefer naming the "terminal_view_autoclose_too" something like "terminal_view_keep_open" instead ;-).

If you could describe this feature in the README right above the "Common problems" section as well that would be great.

**Comment by rwols** [comment]
It doesn't always flush the last remaining output when the terminal closes down, I'll have to investigate and work on it a little more. I'll also update the readme.

**Comment by rwols** [comment]
I think this works now.

Some things of note:

1. I only check if the shell is running in the update thread
2. I removed the check to see if the shell is running in LinuxPty.receive_output
3. When the update thread exits because the shell is not running, a last call to `self._poll_shell_output(timeout=0)` is made (this works for some reason)
4. in SublimeTerminalBuffer.close, if the view needs to stay open, I flush those last remaining bytes that we got with (3) via self.update_view.
5. At this point TerminalView and LinuxPty should be gone, but SublimeTerminalBuffer will stay alive until the view closes. SublimeTerminalBuffer does deregister itself from its manager.
6. in TerminalViewKeypress, I have to check for every invocation if the SublimeTerminalBuffer can be found via its manager. This prevents invalid keycallbacks when the shell has already closed but SublimeTerminalBuffer stays alive.

**Comment by rwols** [comment]
By the way, are these tests supposed to fail? I'm not sure if I should dig into that...

**Comment by Wramberg** [comment]
No but I messed up the devel branch with the new pty approach so I don't think its your code. I'll get that sorted as soon as I have time ;-)

**Comment by Wramberg** [comment]
I think this is a really cool feature but I have some comments about the approach.

#### Generally
I think we should break down the problem a bit and decide where to put responsibilities. Right now we need to disable the automatic restart for the view that is kept open (otherwise it is restarted on project switch or ST restart). This logic needs to be placed in the TerminalView module where it can remove the "terminal_view_active_args" on the view when it would otherwise be closed. For this reason I think the rest of the keep-open logic should be handled by the TerminalView module as well.

#### sublime_terminal_buffer
To do this the sublime_terminal_buffer need to have a new method called deactivate() (or something) that can call

```
self._view.settings().set("terminal_view", False)  # Disable keypresses - view essentially becomes traditional ST3 view
self.update_view()
SublimeBufferManager.deregister(self._view.id())
# Finished message here
```

and then the close method on sublime_terminal_buffer can simply call deactivate() and 

```
sublime.active_window().focus_view(self._view)
sublime.active_window().run_command("close_file")
```

Note that I would prefer changing the terminal_view setting instead of the enabled check in the terminal_keyoress command.

#### TerminalView
I am pretty sure you messed up the normal close down procedure when removing the `self._terminal_buffer.is_open()` check in the runloop. I think we should keep that so everything is shut down when the user closes the view.

I think we should save the keep_open flag on the terminalview class and check it in the stop method whether we should only deactivate the terminal buffer or close it. When closing we should also remove the activate args to ensure the view is not restarted.

Depending on your time I could pull this in as it is and make the changes myself. Let me know what you think.

**Comment by Wramberg** [comment]
If you merge the latest commit on `devel` into your branch all CI tests should pass again ;-)

**Comment by rwols** [comment]
You have a much better overview of the codebase, so if you find the time to fix my mistakes then I'd be happy. You can merge this into devel if you want.

**Comment by Wramberg** [comment]
Wouldnt call them mistakes more like alternative approaches ;-) I'll pull this in and take a look. Thanks for the contribution @rwols - looks like a nice feature.

**Comment by Wramberg** [comment]
Just played around with this - this feature is really cool :-D
@rwols would you mind checking my merciless refactoring in 3a96571d11ed7764b2ad7029148d5ef78aa50d87 for any regressions ? Note the informative close message that differentiates between normal exits and signals :sunglasses:

**Comment by rwols** [comment]
I agree with these changes, nice job.

**Pull request merged**
