### PR TITLE
Pyte v0.7-dev

### PR DESCRIPTION
**Pull request by randy3k**
I understand that you might not want to upgrade pyte to its beta dev version now, but pyte 0.5.2 doesn't handle OSC sequence very well. This 1337 OSC sequence is very common for iTerm2 users on macOS. 

This PR is more for future references or other potential users.

Before
screen shot 2017-07-30 at 8 06 15 pm

After
screen shot 2017-07-30 at 8 05 19 pm

### CODE REVIEW

**Comment by randy3k** [comment]
By the way, it seems that the resize functionality is broken, what kind of optimization have you done to `CustomHistoryScreen`?

**Comment by Wramberg** [comment]
We are on 0.5.2 due some bugs I saw in 0.6 and forward. See ce1b6a096cb2604a74f4152b33bbfbe940f8483d for details.

Are you using newer Pyte when seeing the resize issues ? It works fine for me on `devel`.

**Comment by randy3k** [comment]
Ya, I am talking the newer pyte v0.7-dev. I am trying to understand pyte in order to fix it.

**Comment by Wramberg** [comment]
If I recall correctly resizing isnt working in pyte 0.5.2 either. Thats why I have implemented my own (copied mostly from a previous version of pyte).

I am still considering looking further into the gateone terminal as well.

**Comment by randy3k** [comment]
no point to keep this open

**Comment by Wramberg** [comment]
We can discuss then again after I've looked into gateone a little more. If gateone doesnt work out after all we definitely need to look into newer pyte version.

**Comment by randy3k** [comment]
Sounds reasonable, good job btw :+1:

**Pull request closed without merging**
